### ISSUE TITLE
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills

### ISSUE THREAD

**Issue by suisui-er** [flyerH/react-canvas-nest#3]
This browser doesn't support requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills.
ie9下面报这个错，

**Comment by flyerH** [comment]
我试了一下，兼容ie9需要装[raf](https://www.npmjs.com/package/raf),[scrollingelement](https://www.npmjs.com/package/scrollingelement)这两个polyfill，会增加体积，所以我就不加了，你可以装这两个包，然后
```
import 'raf/polyfill';
import 'scrollingElement';
```

**Comment by suisui-er** [comment]
好的，我之前是把ie10以下剔出去了，哈哈，谢谢
