### ISSUE TITLE
WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by hcygit** [flyerH/react-canvas-nest#7]
call window directly will lead to fail while building in production as below:
```
  WebpackError: ReferenceError: window is not defined

  - react-canvas-nest.min.js:1 Object../node_modules/react-canvas-nest/dist/react-canvas-nest.min.js
```

the solution to solve this issue is to check if window is available everytime you need it,
```
typeof window !== 'undefined' && window.[event]
```

**Comment by flyerH** [comment]
https://github.com/webpack/webpack/issues/6784#issuecomment-375941431
Thanks for your report, I have tried to fix it in `react-canvas-nest@1.1.1-beta.0`.
If it work, I will release the official version.
